### ISSUE TITLE
In mapper.py -> color_point_2_depth_point()  error

### ISSUE THREAD

**Issue by Max-918** [KonstantinosAng/PyKinect2-PyQtGraph-PointClouds#1]
In color_point_2_depth_point() function, [depth_x, depth_y] ->[-inf, -inf]
So it leads to the following result：

line 123, in color_point_2_depth_point
    return [int(depth_x), int(depth_y)]
OverflowError: cannot convert float infinity to integer

If it is convenient for you, please tell me how can I solve this problem?

**Comment by KonstantinosAng** [comment]
Sorry for not replying, i have answered this error in this issue:

https://github.com/Kinect/PyKinect2/issues/80

**Comment by KonstantinosAng** [comment]
I have made real time point clouds with the Kinect. If you know the place of the manipulator you can isolate the pointcloud, otherwise you can put a marker on the robotic manipulator and track the location of the marker

https://github.com/KonstantinosAng/PyKinect2-PyQtGraph-PointClouds

**Comment by Max-918** [comment]
Thanks！
