### ISSUE TITLE
Why can't the image be displayed when the mapper.py is running ?

### ISSUE THREAD

**Issue by WangXingfang** [KonstantinosAng/PyKinect2-PyQtGraph-PointClouds#2]
'Test Color View' and 'Test Depth View' is not displayed when I run the program called "mapper.py".
I didn't find out where the problem was. It would be great if you help me on it.

**Comment by KonstantinosAng** [comment]
Sorry for taking too long to answer. Have you installed all dependecies from the mapper.py repository ?

Mapper.py repository:
https://github.com/KonstantinosAng/PyKinect2-Mapper-Functions

Maybe download the newer version and try again.
