### ISSUE TITLE
how to import the dynamic point cloud to a numpy array

### ISSUE THREAD

**Issue by VividCycle** [KonstantinosAng/PyKinect2-PyQtGraph-PointClouds#6]
I wanna use the “Cloud” class to get the dynamic deep point cloud and save the cloud to a numpy array,how can I do that by using the Cloud class

**Comment by KonstantinosAng** [comment]
You do not need this repo to only get a pointCloud from Kinect in a numpy array. You can use my other library for this kind of stuff:

https://github.com/KonstantinosAng/PyKinect2-Mapper-Functions


Using the mapper class you can do:

`
from pykinect2.PyKinectV2 import *
from pykinect2 import PyKinectV2
from pykinect2 import PyKinectRuntime
import mapper

kinect = PyKinectRuntime.PyKinectRuntime(PyKinectV2.FrameSourceTypes_Color|PyKinectV2.FrameSourceTypes_Depth|PyKinectV2.FrameSourceTypes_Body|PyKinectV2.FrameSourceTypes_BodyIndex)

while True:
  if kinect.has_new_depth_frame() and kinect.has_new_color_frame():
    world_points = mapper.color_2_world(self._kinect, self._kinect._depth_frame_data, _CameraSpacePoint, as_array=False)
    world_points = ctypes.cast(self._world_points, ctypes.POINTER(ctypes.c_float))
    world_points = np.ctypeslib.as_array(self._world_points, shape=(self._kinect.color_frame_desc.Height * self._kinect.color_frame_desc.Width, 3))

    dynamic_point_cloud = np.ndarray(shape=(len(self._world_points), 3), dtype=np.float32)
    dynamic_point_cloud[:, 0] = self._world_points[:, 0] * 1000
    dynamic_point_cloud[:, 1] = self._world_points[:, 2] * 1000
    dynamic_point_cloud[:, 2] = self._world_points[:, 1] * 1000
`

The dynamic point cloud is a numpy array containing the world coordinates of Kinect with color rgb.
the dynamic_point_cloud[0] is the x coordinates, the dynamic_point_cloud[1] is the y coordinates and the dynamic_point_cloud[2] is the z coordinates


DISCLAIMER: As I do not have a Kinect device anymore, I cannot run this code and test it, but I think it will work.

**Comment by VividCycle** [comment]
> You do not need this repo to only get a pointCloud from Kinect in a numpy array. You can use my other library for this kind of stuff:
> 
> https://github.com/KonstantinosAng/PyKinect2-Mapper-Functions
> 
> Using the mapper class you can do:
> 
> ` from pykinect2.PyKinectV2 import * from pykinect2 import PyKinectV2 from pykinect2 import PyKinectRuntime import mapper
> 
> kinect = PyKinectRuntime.PyKinectRuntime(PyKinectV2.FrameSourceTypes_Color|PyKinectV2.FrameSourceTypes_Depth|PyKinectV2.FrameSourceTypes_Body|PyKinectV2.FrameSourceTypes_BodyIndex)
> 
> while True: if kinect.has_new_depth_frame() and kinect.has_new_color_frame(): world_points = mapper.color_2_world(self._kinect, self._kinect._depth_frame_data, _CameraSpacePoint, as_array=False) world_points = ctypes.cast(self._world_points, ctypes.POINTER(ctypes.c_float)) world_points = np.ctypeslib.as_array(self._world_points, shape=(self._kinect.color_frame_desc.Height * self._kinect.color_frame_desc.Width, 3))
> 
> ```
> dynamic_point_cloud = np.ndarray(shape=(len(self._world_points), 3), dtype=np.float32)
> dynamic_point_cloud[:, 0] = self._world_points[:, 0] * 1000
> dynamic_point_cloud[:, 1] = self._world_points[:, 2] * 1000
> dynamic_point_cloud[:, 2] = self._world_points[:, 1] * 1000
> ```
> 
> `
> 
> The dynamic point cloud is a numpy array containing the world coordinates of Kinect with color rgb. the dynamic_point_cloud[0] is the x coordinates, the dynamic_point_cloud[1] is the y coordinates and the dynamic_point_cloud[2] is the z coordinates
> 
> DISCLAIMER: As I do not have a Kinect device anymore, I cannot run this code and test it, but I think it will work.

**Comment by VividCycle** [comment]
Thank you for your reply and help so much!

**Comment by VividCycle** [comment]
> You do not need this repo to only get a pointCloud from Kinect in a numpy array. You can use my other library for this kind of stuff:
> 
> https://github.com/KonstantinosAng/PyKinect2-Mapper-Functions
> 
> Using the mapper class you can do:
> 
> ` from pykinect2.PyKinectV2 import * from pykinect2 import PyKinectV2 from pykinect2 import PyKinectRuntime import mapper
> 
> kinect = PyKinectRuntime.PyKinectRuntime(PyKinectV2.FrameSourceTypes_Color|PyKinectV2.FrameSourceTypes_Depth|PyKinectV2.FrameSourceTypes_Body|PyKinectV2.FrameSourceTypes_BodyIndex)
> 
> while True: if kinect.has_new_depth_frame() and kinect.has_new_color_frame(): world_points = mapper.color_2_world(self._kinect, self._kinect._depth_frame_data, _CameraSpacePoint, as_array=False) world_points = ctypes.cast(self._world_points, ctypes.POINTER(ctypes.c_float)) world_points = np.ctypeslib.as_array(self._world_points, shape=(self._kinect.color_frame_desc.Height * self._kinect.color_frame_desc.Width, 3))
> 
> ```
> dynamic_point_cloud = np.ndarray(shape=(len(self._world_points), 3), dtype=np.float32)
> dynamic_point_cloud[:, 0] = self._world_points[:, 0] * 1000
> dynamic_point_cloud[:, 1] = self._world_points[:, 2] * 1000
> dynamic_point_cloud[:, 2] = self._world_points[:, 1] * 1000
> ```
> 
> `
> 
> The dynamic point cloud is a numpy array containing the world coordinates of Kinect with color rgb. the dynamic_point_cloud[0] is the x coordinates, the dynamic_point_cloud[1] is the y coordinates and the dynamic_point_cloud[2] is the z coordinates
> 
> DISCLAIMER: As I do not have a Kinect device anymore, I cannot run this code and test it, but I think it will work.

Thank you for your help!
