### ISSUE TITLE
Met problem when using function color_point_2_depth_point

### ISSUE THREAD

**Issue by Porthoos** [KonstantinosAng/PyKinect2-PyQtGraph-PointClouds#7]
When I am using the function color_point_2_depth_point in mapper.py, I sometimes met the problem like this but not everytime.
![image](https://user-images.githubusercontent.com/74708619/170697412-0edd3c23-576e-4247-a6b5-7824d4b94e12.png)
can you help me why this would happen?

**Comment by KonstantinosAng** [comment]
Hello, the problem is with int(center_x), int(center_y). you cannot be sure that the Kinect values will always be numeric (float or int). The kinect is susceptible to external noise, such as light and reflections, and its values can overflow and return as '-inf'

**Comment by KonstantinosAng** [comment]
Thus, the error cannot convert float infinity to int

**Comment by KonstantinosAng** [comment]
i suggest you do int(center_x) if center_x != float('-inf') and center_x != float('inf') else center_x, and the same for center_y

or better:

int(center_x) if center_x != float('-inf') and center_x != float('inf') else 0

**Comment by Porthoos** [comment]
Thank you for your reply.
I made sure that center_x and center_y are not inf, they are the point of detected object in color frame.
Is there other possible reasons for this error>

**Comment by KonstantinosAng** [comment]
I have come across this error before, and its best to have a sufficient distance from the kinect sensor (at least 1 meter) and its best to stay at the center of the depth/rgb image, because the distortion increases as you get to the side of the depth/rgb image and make sure that there are no reflective surfaces that cause distortion on the kinect path

**Comment by Porthoos** [comment]
Your suggestions are valuable, I will try them.
Can I contact with you if I meet some other problems?
Thank you.

**Comment by KonstantinosAng** [comment]
You can, but keep in mind that I do not have a Kinect anymore and I cannot assist in everything.

**Comment by KonstantinosAng** [comment]
I made a change to the repo library to handle this, do a git pull and try again. You don't have to change anything.

**Comment by Porthoos** [comment]
The change helped that no more error occurs.
But now I meet a new problem.
![image](https://user-images.githubusercontent.com/74708619/170825605-d3870cd8-f0a6-4c43-9cee-a6e8b5a7ff13.png)
As you can see in this picture, the box is the input point to function `depth_point_2_world_point`, I have randomly changed the object position, but the function returns the exact same world.z value as the arrow points.
I have also changed the background and light condition for many times but they don't help.
Have you ever met this problem before?

**Comment by KonstantinosAng** [comment]
I cannot say for sure what is going on, as when calling the depth_point_2_world_point function I just call the Kinect's transformation function MapDepthPointToCameraSpace and return the values, so I cannot know for sure what this function does internally.

But what I know is that the depth point is actually the z (distance from the Kinect Sensor) so you can actually get the z value like this:

 if (int(depth_y) * 512 + int(depth_x)) < 512 * 424:
                    world_z = float(depth[int(depth_y) * 512 + int(depth_x)])  # mm

where depth is just:

depth = kinect.get_last_depth_frame()
